parameters:
#    como_tne_user.example.class: Como\TneUserBundle\Example

services:
#    como_tne_user.example:
#        class: %como_tne_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
