parameters:
#    como_accommodation.example.class: Como\AccommodationBundle\Example

services:
#    como_accommodation.example:
#        class: %como_accommodation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    como.accommodation.admin.product:
        class: Como\AccommodationBundle\Admin\ProductAdmin
        arguments: [null, Como\AccommodationBundle\Entity\Product, ComoAccommodationBundle:ProductAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Operators, label: ATDW }        

    como.accommodation.admin.productmanual:
        class: Como\AccommodationBundle\Admin\ProductManualAdmin
        arguments: [null, Como\AccommodationBundle\Entity\Product, ComoAccommodationBundle:ProductManualAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Operators, label: Manual Data}        

    como.accommodation.admin.productexternal:
      class: Como\AccommodationBundle\Admin\ProductExternalAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Operators, label: TXA Data }
      arguments: [null, Como\AccommodationBundle\Entity\ProductExternal, ComoAccommodationBundle:ProductExternalAdmin]
        