parameters:
#    como_accommodation.example.class: Como\AccommodationBundle\Example

services:
#    como_accommodation.example:
#        class: %como_accommodation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    como.accommodation.admin.product:
        class: Como\AccommodationBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Operators, label: ATDW }
        arguments: [null, Como\AccommodationBundle\Entity\Product, ComoAccommodationBundle:ProductAdmin]