sonata_user:
    security_acl:           false

    google_authenticator:
        enabled: true
        server:  localhost
        
    impersonating:
        route:                page_slug
        parameters:           { path: / }

    class:                  # Entity Classes
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group

    admin:                  # Admin Classes
        user:
            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata.user.profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]

#sonata_user:
#    security_acl:             false
#    table:
#        user_group:           fos_user_user_group
#
#    impersonating:
#        route:                page_slug
#        parameters:           { path: / }
#
#    google_authenticator:
#        server:               %sonata_user.google_authenticator.server%
#        enabled:              true
#
#    manager_type:             orm
#
#    profile:
#        form:
#            type:                 sonata_user_profile
#            handler:              sonata.user.profile.form.handler.default
#            name:                 sonata_user_profile_form
#            validation_groups:
#                # Defaults:
#                - Profile
#                - Default
