como_front_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ComoFrontBundle:Default:index }
    
como_front_details:
    pattern:  /details/{id}
    defaults: { _controller: ComoFrontBundle:Default:details } 
    requirements: 
      id: \d+
