<?php

namespace Como\AccommodationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductExternalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductExternalRepository extends EntityRepository
{
}
