<?php

namespace Como\AccommodationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProductList()
    {
        $qb = $this->createQueryBuilder('j')
        ->setMaxResults(5);
        
        $query = $qb->getQuery();

        return $query->getResult();
    }
}
