parameters:
#    como_tne.example.class: Como\TneBundle\Example

services:
#    como_tne.example:
#        class: %como_tne.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
