parameters:
    como.indexer: Como\SearchBundle\Listener\Indexer
    como.search:  Como\SearchBundle\Utils\Search
    como.index.entities:
      - { Job: [position, company, location, description] }
      - { Category: [name] }
    como.index.results:      
      - [ Job, Category ]
services:
    lucene.listener:
            class: %como.indexer%
            arguments: ["@search_indexer", %como.index.entities%, %como.index.results%  ]
            tags:
                - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }

    search_indexer:
        class: %como.search%